version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - nestjs
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  postgres:
    container_name: pg_db
    restart: always
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: production
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
  nestjs:
    container_name: nestjs
    restart: always
    depends_on:
      - postgres
    build: ./server
    ports:
      - "3000:3000"
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3030:80"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ildar@mail.ru
      PGADMIN_DEFAULT_PASSWORD: ildar
    ports:
      - "5050:80"
volumes:
  postgres-data:
